import Link from "next/link";
import { notFound } from "next/navigation";
import { getCampaign } from "@/app/_lib/campaigns/queries";
import { getPendingVariants } from "@/app/_lib/backend/campaigns";
import { ApproveRejectForm } from "./ApproveRejectForm";

type Params = Promise<{ id: string }>;

export default async function PendingPage({ params }: { params: Params }) {
  const { id } = await params;
  const campaign = await getCampaign(id);
  if (!campaign) notFound();
  const pending = await getPendingVariants(campaign.id);

  return (
    <div className="max-w-4xl">
      <Link
        href={`/campaigns/${campaign.id}`}
        className="text-xs text-ink/50 hover:text-ink/80"
      >
        ← {campaign.name}
      </Link>
      <h1 className="font-serif text-4xl tracking-tight mt-2 mb-1">
        Approval queue
      </h1>
      <p className="text-[10px] font-mono text-ink/40 mb-8">
        {pending.length} pending variant{pending.length === 1 ? "" : "s"}
      </p>

      {pending.length === 0 ? (
        <div className="border border-ink/10 p-16 text-center">
          <p className="font-serif text-2xl text-ink/70">Nothing waiting.</p>
          <p className="text-sm text-ink/50 mt-2">
            New variants generated by research will appear here.
          </p>
        </div>
      ) : (
        <ul className="space-y-6">
          {pending.map((v) => {
            const parent = campaign.variants.find((x) => x.id === v.parent_id);
            return (
              <li
                key={v.id}
                className="border border-ink/15 p-6 grid grid-cols-2 gap-8"
              >
                <div>
                  <div className="text-[10px] font-mono uppercase tracking-[0.14em] text-ink/40 mb-2">
                    Parent {parent ? `#${parent.id}` : ""}
                  </div>
                  <div className="font-serif text-lg leading-tight mb-3">
                    {parent?.subject ?? "(unknown)"}
                  </div>
                  <pre className="text-xs text-ink/60 whitespace-pre-wrap font-sans">
                    {parent?.body ?? ""}
                  </pre>
                </div>
                <div>
                  <div className="text-[10px] font-mono uppercase tracking-[0.14em] text-ink/40 mb-2">
                    Candidate #{v.id}
                  </div>
                  <div className="font-serif text-lg leading-tight mb-3">
                    {v.subject}
                  </div>
                  <pre className="text-xs text-ink/80 whitespace-pre-wrap font-sans mb-4">
                    {v.body}
                  </pre>
                  <ApproveRejectForm campaignId={campaign.id} variantId={v.id} />
                </div>
              </li>
            );
          })}
        </ul>
      )}
    </div>
  );
}
